/* 
 * Module:        CommonVoucherQueries.java 
 * Author:        S. Muthu Subramaniam
 * Date Written:  Oct - 2003 
 * Description:   This class has the Queries as Constants, which all the Voucher will Be Using
 * Revision Log   (mm/dd/yy initials description) 
 * -------------------------------------------------------- 
 * mm/dd/yy xxx  What you changed … 
*/

package FCIPAY.HRMS.DATAACCESSTIER.SQLQueries;

public final class CommonVoucherQueries 
{
   public static final String sql_compLocId="SELECT COUNT(*) AS TOTAL from COM_LOC_MST where LOC_ID=? AND GL_INST_SITE='Y'";
   public static final String sql_getPeriod="SELECT PRD_ID,PRD_DESC,TO_CHAR(START_DT,'MM/DD/YYYY') AS START_DT,TO_CHAR(END_DT,'MM/DD/YYYY') AS END_DT from FIN_CLNDR_PRD where CLNDR_ID IN (select CLNDR_ID from FIN_CLNDR_MST where CLNDR_STATUS_GBL='CALSTATUS$OPEN' AND LOC_ID=?) AND PRD_STATUS='A' AND START_DT < sysdate";// ORDER BY PRD_ID";
   public static final String sql_getPeriodBankCash="SELECT PRD_ID,PRD_DESC,TO_CHAR(START_DT,'MM/DD/YYYY') AS START_DT,TO_CHAR(END_DT,'MM/DD/YYYY') AS END_DT from FIN_CLNDR_PRD where CLNDR_ID IN (select CLNDR_ID from FIN_CLNDR_MST where CLNDR_STATUS_GBL='CALSTATUS$OPEN' AND CLNDR_OPEN_IND_GBL='CALSTATE$CUR' AND LOC_ID=?) AND PRD_STATUS='A' AND START_DT < sysdate";// ORDER BY PRD_ID";
   public static final String sql_getDocLoc="SELECT LOC_SDESC FROM COM_LOC_MST WHERE LOC_ID=?";
   public static final String sql_getNJVVoucherType="SELECT GBL_CODE FROM COM_GBL_DTL WHERE CODE_SDESC='NJV'";
   
   public static final String sql_checkAcctId="SELECT NVL(USI_FLG,'N') AS USI_FLG,NVL(CHG_FLG,'N') AS CHG_FLG,NVL(CC_FLG,'N') AS CC_FLG,NVL(CTRL_ACCT,'N') AS CTRL_ACCT,NVL(CTRL_TYPE_FLG,'Z') AS CTRL_TYPE  FROM FIN_ACCT_MST WHERE ACCT_ID=? AND (ACCT_STATUS='A' AND CB_ACCT_FLG IS NULL )";
   //AND PLBS_TYPE_GBL NOT IN ('PLBSTYPE$IUA'))"; //TEMPORARY FOR IUA VOUCHERS
   public static final String sql_checkAcctId_CJV="SELECT NVL(CHG_FLG,'N') AS CHG_FLG FROM FIN_ACCT_MST WHERE  ACCT_ID=? AND (ACCT_STATUS='A' AND CB_ACCT_FLG IS NULL AND PLBS_TYPE_GBL NOT IN ('PLBSTYPE$PL','PLBSTYPE$IUA')) AND ACCT_ID IN (SELECT ACCT_ID from FIN_ACCT_MST where ((ACCT_ID >= 10000 AND ACCT_ID <= 10999) OR (ACCT_ID >= 14000 AND ACCT_ID <= 14999)) AND (CTRL_ACCT IS NULL OR CTRL_ACCT='N'))";
   public static final String sql_checkAcctId_Receipt="SELECT NVL(USI_FLG,'N') AS USI_FLG,NVL(CHG_FLG,'N') AS CHG_FLG,NVL(CC_FLG,'N') AS CC_FLG,NVL(CTRL_ACCT,'N') AS CTRL_ACCT,NVL(CTRL_TYPE_FLG,'Z') AS CTRL_TYPE  FROM FIN_ACCT_MST WHERE ACCT_ID=? AND (ACCT_STATUS='A'  AND PLBS_TYPE_GBL NOT IN ('PLBSTYPE$PL','PLBSTYPE$IUA','PLBSTYPE$IUAS'))";   
   public static final String sql_checkAcctId_CashPayAdvice="SELECT NVL(USI_FLG,'N') AS USI_FLG,NVL(CHG_FLG,'N') AS CHG_FLG,NVL(CC_FLG,'N') AS CC_FLG,NVL(CTRL_ACCT,'N') AS CTRL_ACCT,NVL(CTRL_TYPE_FLG,'Z') AS CTRL_TYPE  FROM FIN_ACCT_MST WHERE ACCT_ID=? AND (ACCT_STATUS='A'  AND PLBS_TYPE_GBL NOT IN ('PLBSTYPE$PL','PLBSTYPE$IUA','PLBSTYPE$IUAS') AND (CTRL_TYPE_FLG!='V' OR CTRL_TYPE_FLG IS NULL))";      
   public static final String sql_checkAcctId_IAV="SELECT NVL(USI_FLG,'N') AS USI_FLG,NVL(CHG_FLG,'N') AS CHG_FLG,NVL(CC_FLG,'N') AS CC_FLG,NVL(CTRL_ACCT,'N') AS CTRL_ACCT,NVL(CTRL_TYPE_FLG,'Z') AS CTRL_TYPE  FROM FIN_ACCT_MST WHERE ACCT_ID=? AND (ACCT_STATUS='A' AND CB_ACCT_FLG IS NULL AND PLBS_TYPE_GBL NOT IN ('PLBSTYPE$PL','PLBSTYPE$IUA') AND (CTRL_TYPE_FLG!='V' OR CTRL_TYPE_FLG IS NULL))";
   public static final String sql_checkAcctId_OJV="SELECT NVL(USI_FLG,'N') AS USI_FLG,NVL(CHG_FLG,'N') AS CHG_FLG,NVL(CC_FLG,'N') AS CC_FLG,NVL(CTRL_ACCT,'N') AS CTRL_ACCT,NVL(CTRL_TYPE_FLG,'Z') AS CTRL_TYPE  FROM FIN_ACCT_MST WHERE ACCT_ID=? AND (ACCT_STATUS='A' AND CB_ACCT_FLG IS NULL AND PLBS_TYPE_GBL NOT IN ('PLBSTYPE$PL') AND (CTRL_TYPE_FLG!='E' OR CTRL_TYPE_FLG IS NULL))";   
   
   public static final String sql_checkOrderId_WO="SELECT A.WO_ID AS WO_ID,A.VEN_ID AS VEN_ID,B.VEN_CODE AS VEN_CODE FROM FIN_WO_MST_HDR A,COM_VEN_MST B WHERE LOWER(A.WO_NO)=? AND A.LOC_ID=? AND A.WO_STATUS_GBL='WOSTATUS$A' AND A.WO_STATE_GBL='WOSTATE$1'  AND A.CTRL_FLG_GBL='M$GL' AND A.VEN_ID=B.VEN_ID";
   public static final String sql_checkOrderId_PO="SELECT A.PO_ID AS PO_ID,A.VEN_ID AS VEN_ID,B.VEN_CODE AS VEN_CODE FROM CMM_PO_MST_F A,COM_VEN_MST B WHERE LOWER(A.PO_NO)=? AND A.LOC_ID=? AND A.PO_STATUS_GBL='POSTATUS$A' AND A.PO_STATE_GBL='POSTATE$1' AND A.CTRL_FLG_GBL='M$GL' AND A.VEN_ID=B.VEN_ID";   
   public static final String sql_checkVenId="SELECT VEN_ID FROM COM_VEN_MST WHERE LOWER(VEN_CODE)=? AND STATUS_FLG='A' AND VEN_CAT_GBL=?";
   public static final String sql_checkEmpId="SELECT EMP_NO FROM HRM_EMPLOYEE WHERE EMP_NO=? AND (EMP_STATUS_FLG='A' OR EMP_STATUS_FLG='a') ";
   public static final String sql_checkChargeId="SELECT COUNT(CH_ID) AS TOTAL FROM COM_CH_LOC_MST WHERE CH_ID=?";
   public static final String sql_checkCostCenterId="SELECT CCSGRP_ID FROM COM_CCSGRP_MST WHERE CCSGRP_CODE=? AND STATUS_FLG='A'";
   public static final String sql_checkUSI_Code="SELECT USI_NO FROM CMM_USI_MST WHERE USI_NO=? AND LOC_CODE=?";
//   sql_checkOrderId_WO,sql_checkOrderId_PO,sql_getPOrderNo,sql_getWOrderNo ------------ QUERIES MODIFIED LOC_ID IS ADDED. STILL SHOULD BE MODIFED IN RESPECTIVE CLASSES
   public static final String sql_getNewVoucherId="SELECT get_id(?,'FIN_VOUCHER_HDR') AS NEXTID FROM DUAL";
   public static final String sql_getNewVoucherNo="SELECT PARAM_VOUCHER_NO FROM FIN_VOUCHER_PARAMS_VHNO WHERE LOC_ID=? AND PARAM_TYPE_GBL=?";

   public static final String sql_getPOrderNo="SELECT PO_NO FROM CMM_PO_MST_F WHERE PO_ID=? AND LOC_ID=? AND PO_STATUS_GBL='POSTATUS$A' AND PO_STATE_GBL='POSTATE$1'  AND CTRL_FLG_GBL='M$GL'";
   public static final String sql_getWOrderNo="SELECT WO_NO FROM FIN_WO_MST_HDR WHERE WO_ID=? AND LOC_ID=? AND WO_STATUS_GBL='WOSTATUS$A' AND WO_STATE_GBL='WOSTATE$1'  AND CTRL_FLG_GBL='M$GL'";
   public static final String sql_getVenCode="SELECT VEN_CODE,VEN_CAT_GBL FROM COM_VEN_MST WHERE VEN_ID=";
   public static final String sql_getEmpNo="SELECT EMP_NO FROM HRM_EMPLOYEE WHERE EMP_NO=? AND (EMP_STATUS_FLG='A' OR EMP_STATUS_FLG='a')";   
   public static final String sql_getCostCenterCode="SELECT CCSGRP_CODE FROM COM_CCSGRP_MST WHERE CCSGRP_ID=";
   public static final String sql_UpdateSrNo="UPDATE FIN_VOUCHER_DTL SET VOUCHER_TXN_NO=? WHERE VOUCHER_ID=?";

   public static final String sql_UpdateParamVoucherNo="UPDATE FIN_VOUCHER_PARAMS_VHNO SET PARAM_VOUCHER_NO=? WHERE LOC_ID=? AND PARAM_TYPE_GBL=?";

   public static final String sql_getFinTrType="SELECT TR_ID,TR_DESC AS TR_SDESC FROM FIN_TR_TYPE WHERE TR_SDESC_GBL='TRREQTYPE$A' ORDER BY TR_ID";
   public static final String sql_getEmployee="SELECT EMP_NO,EMP_FST_NAME,NVL(EMP_MDL_NAME,' ') AS EMP_MDL_NAME,NVL(EMP_LST_NAME,' ') AS EMP_LST_NAME FROM HRM_EMPLOYEE WHERE EMP_STATUS_FLG='A'AND EMP_UNIT_ID=? ORDER BY EMP_NO";
   public static final String sql_GetSponsorGbltypes="SELECT GBL_CODE,CODE_DESC FROM COM_GBL_DTL WHERE GBL_TYPE='FTRSPONSOR' ORDER BY GBL_CODE";

   public static final String sql_getNewAdvId="SELECT nvl(FIN_TR_ADV_HDR_NUM_SEQ.NEXTVAL,0) AS SEQ_NO,nvl(get_id(?,'FIN_TR_ADV_HDR'),0) AS NEXTID FROM DUAL";

   public static final String VALIDATE_VH_DATE = "select 'Y' result from dual where " + 
    "to_date(?, 'dd/mm/yyyy') >= (select to_char(nvl(max(posting_dt), to_date(?, 'dd/mm/yyyy'))) from FIN_VOUCHER_HDR where loc_id = ? " +
    "and txn_status_gbl = 'VHSTAT$6')";

   public static final String sql_getAcctId_ForTrId_IAV="SELECT ADV_ACCT_ID AS ACCT_ID FROM FIN_TR_TYPE WHERE TR_ID=?";

   public static final String sql_UpdateDetailsSetNULL="UPDATE FIN_VOUCHER_DTL SET DTL_NRTN=NULL,PO_ID=NULL,WO_ID=NULL,VEN_ID=NULL,EMP_NO=NULL,CH_ID=NULL,USI_CODE=NULL,CCSGRP_ID=NULL,LINK_REF=NULL WHERE VOUCHER_DTL_ID=?";


   public static final String sql_RetrieveRecordsForEdit_Dtl_IDS="SELECT VOUCHER_DTL_ID,VOUCHER_TXN_NO FROM FIN_VOUCHER_DTL WHERE VOUCHER_ID=? ORDER BY VOUCHER_DTL_ID"; // Added USI CODE WHEN DOING THE RECEIPT SCREEN    

   public static final String sql_Delete_Voucher="UPDATE FIN_VOUCHER_HDR SET TXN_STATUS_GBL='VHSTAT$7' WHERE VOUCHER_ID=?";

   public static final String sql_SelectTransactionMode_BPV="SELECT GBL_CODE,CODE_DESC FROM COM_GBL_DTL WHERE TRIM(GBL_TYPE) = 'VHFOR'";

   public static final String sql_SelectTransactionAcctId_BPV="SELECT MST.VH_FOR_GBL,DTL.ACCT_ID FROM FIN_TAX_ACCT_DTL DTL,FIN_TAX_ACCT_MST MST WHERE MST.TAX_ID=DTL.TAX_ID ORDER BY MST.VH_FOR_GBL";

   public static final String sql_getFinancialYear="SELECT TRIM(SUBSTR(TO_CHAR(FROM_DT,'YYYY'),3)) AS FIN_YEAR FROM FIN_CLNDR_MST WHERE CLNDR_STATUS_GBL='CALSTATUS$OPEN' AND CLNDR_OPEN_IND_GBL='CALSTATE$CUR' AND LOC_ID=?";

// USED IN SEARCH SCREEN

   public static final String sql_AcctId_Search_NJV="SELECT ACCT_ID,ACCT_DESC from FIN_ACCT_MST where (ACCT_STATUS='A' AND CB_ACCT_FLG IS NULL ) AND ";
   //AND PLBS_TYPE_GBL NOT IN ('PLBSTYPE$IUA')) AND ";  //Temporary for IUA vouchers
   public static final String sql_AcctId_Search_CJV="SELECT ACCT_ID,ACCT_DESC from FIN_ACCT_MST where (ACCT_STATUS='A' AND CB_ACCT_FLG IS NULL AND PLBS_TYPE_GBL NOT IN ('PLBSTYPE$PL','PLBSTYPE$IUA')) AND ACCT_ID IN (SELECT ACCT_ID from FIN_ACCT_MST where (ACCT_ID >= 10000 AND ACCT_ID <= 10999) OR (ACCT_ID >= 14000 AND ACCT_ID <= 14999)) AND (CTRL_ACCT IS NULL OR CTRL_ACCT='N') AND ";   
   public static final String sql_AcctId_Search_RECEIPT="SELECT ACCT_ID,ACCT_DESC FROM FIN_ACCT_MST WHERE (ACCT_STATUS='A'  AND PLBS_TYPE_GBL NOT IN ('PLBSTYPE$PL','PLBSTYPE$IUA','PLBSTYPE$IUAS')) AND ";
   public static final String sql_AcctId_Search_CahsPayAdvice="SELECT ACCT_ID,ACCT_DESC FROM FIN_ACCT_MST WHERE (ACCT_STATUS='A'  AND PLBS_TYPE_GBL NOT IN ('PLBSTYPE$PL','PLBSTYPE$IUA','PLBSTYPE$IUAS')) AND (CTRL_TYPE_FLG!='V' OR CTRL_TYPE_FLG IS NULL) AND ";   
   public static final String sql_AcctId_Search_IAV="SELECT ACCT_ID,ACCT_DESC from FIN_ACCT_MST where (ACCT_STATUS='A' AND CB_ACCT_FLG IS NULL AND PLBS_TYPE_GBL NOT IN ('PLBSTYPE$PL','PLBSTYPE$IUA') AND (CTRL_TYPE_FLG!='V' OR CTRL_TYPE_FLG IS NULL)) AND ";
   public static final String sql_AcctId_Search_OJV="SELECT ACCT_ID,ACCT_DESC from FIN_ACCT_MST where (ACCT_STATUS='A' AND CB_ACCT_FLG IS NULL AND PLBS_TYPE_GBL NOT IN ('PLBSTYPE$PL') AND (CTRL_TYPE_FLG!='E' OR CTRL_TYPE_FLG IS NULL)) AND ";   

   public static final String sql_SL_EMPL_Search_NJV="SELECT EMP_NO,EMP_FST_NAME || ' ' ||  EMP_MDL_NAME || ' ' || EMP_LST_NAME  AS EMP_FST_NAME FROM HRM_EMPLOYEE WHERE (EMP_STATUS_FLG='A' OR EMP_STATUS_FLG='a')";
   public static final String sql_SL_DR_Search_NJV="SELECT VEN_ID,VEN_CODE,VEN_NAME FROM COM_VEN_MST WHERE (STATUS_FLG='A' AND VEN_CAT_GBL='VENCAT$DR')  AND ";
   public static final String sql_SL_CR_Search_NJV="SELECT VEN_ID,VEN_CODE,VEN_NAME FROM COM_VEN_MST WHERE (STATUS_FLG='A' AND VEN_CAT_GBL='VENCAT$CR')  AND ";
   public static final String sql_CH_Search_NJV="SELECT A.CH_ID AS CH_ID,B.CHG_CODE AS CHG_ID,B.CHG_SDESC AS CHG_SDESC FROM COM_CH_LOC_MST A,COM_CHG_MST B WHERE (A.LOC_ID=?) AND (A.CHG_ID=B.CHG_ID)";
   public static final String sql_CC_Search_NJV="SELECT CCSGRP_ID,CCSGRP_CODE,CCSGRP_DESC FROM COM_CCSGRP_MST WHERE STATUS_FLG='A' AND ";
   public static final String sql_ORD_WO_Search_NJV="SELECT A.WO_ID AS WO_ID,A.WO_NO AS WO_NO,A.ORDER_DTL AS ORDER_DTL,A.VEN_ID AS VEN_ID,B.VEN_CODE AS VEN_CODE FROM FIN_WO_MST_HDR A,COM_VEN_MST B WHERE (A.VEN_ID=B.VEN_ID AND A.WO_STATUS_GBL='WOSTATUS$A' AND A.WO_STATE_GBL='WOSTATE$1') AND A.CTRL_FLG_GBL='M$GL' AND ";
   public static final String sql_ORD_PO_Search_NJV="SELECT A.PO_ID AS PO_ID,A.PO_NO AS PO_NO,A.PO_LDESC AS PO_LDESC,A.VEN_ID AS VEN_ID,B.VEN_CODE AS VEN_CODE FROM CMM_PO_MST_F A,COM_VEN_MST B WHERE (A.VEN_ID=B.VEN_ID AND A.PO_STATUS_GBL='POSTATUS$A' AND A.PO_STATE_GBL='POSTATE$1') AND A.CTRL_FLG_GBL='M$GL' AND ";   
   public static final String sql_USI_Search_PayRec="SELECT USI_ID,USI_NO,USI_DESC AS USI_SDESC FROM CMM_USI_MST WHERE LOC_CODE=";

// USED IN QUERY SCREEN

   public static final String sql_getVoucherDetails_type1="SELECT DISTINCT A.VOUCHER_ID AS V_ID,A.VOUCHER_NO AS V_NO,to_char(A.VOUCHER_DT,'DD/MM/YYYY') AS V_DT,A.DOC_REF AS D_REF,A.DOC_REM AS D_REM,A.TXN_STATUS_GBL AS TXN_STATUS,NVL(A.AUTH_CMNT,' ') AS AUTH_CMNT FROM FIN_VOUCHER_HDR A,FIN_VOUCHER_DTL B WHERE (";
   
}