package FCIPAY.COMMON.DATAACCESSTIER.SQLQueries;

public class EmplGrpRoleAssignQueries  {
    public static final String GET_EMPL_USERLOCID_DETAILS="SELECT HE.EMP_FST_NAME || ' ' || HE.EMP_MDL_NAME || ' ' || HE.EMP_LST_NAME EMP_NAME,SUL.USERLOC_ID LOC_ID FROM HRM_EMPLOYEE HE,SYSADMIN_USER_LOC SUL WHERE SUL.EMP_NO=HE.EMP_NO AND SUL.LOC_STAT_FLG='A' AND SUL.LOC_ID=? AND SUL.EMP_NO=?";
    public static final String GET_MODULES="SELECT DISTINCT SGM.MODULE_GBL MODULE_GBL,CGD.CODE_DESC CODE_DESC FROM SYSADMIN_GRP_MST SGM,COM_GBL_DTL CGD WHERE SGM.MODULE_GBL=CGD.GBL_CODE AND SGM.GRP_STAT_FLG='A' AND SGM.LOC_ID=?";
    public static final String GET_ROLES="SELECT GBL_CODE,CODE_DESC FROM COM_GBL_DTL WHERE GBL_CODE LIKE '%ROLE%'";
    public static final String GET_GROUPS="SELECT SGM.GRP_SDESC GRP_SDESC,SGM.GRP_DESC GRP_DESC  FROM SYSADMIN_GRP_MST SGM WHERE SGM.GRP_STAT_FLG='A' AND SGM.LOC_ID=? AND SGM.MODULE_GBL=? AND SGM.GRP_SDESC NOT IN (SELECT DISTINCT GRP_SDESC FROM SYSADMIN_GRP_EMP_MST WHERE EMP_NO=?)";
/*    public static final String GET_ROLES_ROWS="SELECT SERM.EMPROLE_ID,SERM.SCREEN_SDESC,SERM.ROLE_ID_GBL,SSM.SCREEN_DESC FROM SYSADMIN_EMP_ROLE_MST SERM,SYSADMIN_SCREEN_MST SSM WHERE SERM.SCREEN_SDESC=SSM.SCREEN_SDESC AND USERLOC_ID=? AND ROLE_ID_GBL!=? AND SSM.MODULE_GBL=? " 
                    + " UNION " 
                    + " SELECT 0 AS EMPROLE_ID,SSM.SCREEN_SDESC,' ' AS ROLE_ID_GBL,SSM.SCREEN_DESC FROM SYSADMIN_SCREEN_MST SSM WHERE SSM.SCREEN_SDESC NOT IN (SELECT SCREEN_SDESC FROM SYSADMIN_EMP_ROLE_MST WHERE USERLOC_ID=? AND ROLE_ID_GBL=?) AND SSM.MODULE_GBL=?";*/
    public static final String INSERT_GROUPS="INSERT INTO SYSADMIN_GRP_EMP_MST (GRP_ID,EMP_NO,GRP_SDESC,CREATED_USER,CREATED_SITE,CREATED_DT,USERLOC_ID) VALUES (GET_ID(?,'SYSADMIN_GRP_EMP_MST'),?,?,?,?,SYSDATE,?)";
    public static final String INSERT_ASSIGN_ROLES="INSERT INTO SYSADMIN_EMP_ROLE_MST (EMPROLE_ID,USERLOC_ID,ROLE_ID_GBL,SCREEN_SDESC,CREATED_USER,CREATED_SITE,CREATED_DT) VALUES (GET_ID(?,'SYSADMIN_EMP_ROLE_MST'),?,?,?,?,?,SYSDATE)";
    public static final String UPDATE_ASSIGN_ROLES="UPDATE SYSADMIN_EMP_ROLE_MST SET ROLE_ID_GBL=?,MODIFIED_USER=?,MODIFIED_SITE=?,MODIFIED_DT=SYSDATE WHERE EMPROLE_ID=?";

    public static final String GET_ROLES_ROWS="SELECT SERM.EMPROLE_ID EMPROLE_ID,SERM.SCREEN_SDESC SCREEN_SDESC,SERM.ROLE_ID_GBL ROLE_ID_GBL,SSM.SCREEN_DESC SCREEN_DESC FROM SYSADMIN_EMP_ROLE_MST SERM,SYSADMIN_SCREEN_MST SSM WHERE SERM.SCREEN_SDESC=SSM.SCREEN_SDESC AND SERM.USERLOC_ID=? AND SSM.MODULE_GBL=? AND ROLE_ID_GBL!=? " +
            " UNION " +
            " SELECT 0 AS EMPROLE_ID,SSM.SCREEN_SDESC,' ' AS ROLE_ID_GBL,SSM.SCREEN_DESC FROM SYSADMIN_SCREEN_MST SSM WHERE (SSM.SCREEN_SDESC NOT IN ( " +
            " SELECT SCREEN_SDESC FROM SYSADMIN_EMP_ROLE_MST WHERE USERLOC_ID=? AND ROLE_ID_GBL=? " +
            " MINUS " +
            " SELECT SERM.SCREEN_SDESC FROM SYSADMIN_EMP_ROLE_MST SERM,SYSADMIN_SCREEN_MST SSM WHERE SERM.SCREEN_SDESC=SSM.SCREEN_SDESC AND SERM.USERLOC_ID=? AND SSM.MODULE_GBL=? AND ROLE_ID_GBL!=?) " +
            " AND SSM.SCREEN_SDESC NOT IN (" +
            " SELECT SERM.SCREEN_SDESC FROM SYSADMIN_EMP_ROLE_MST SERM,SYSADMIN_SCREEN_MST SSM WHERE SERM.SCREEN_SDESC=SSM.SCREEN_SDESC AND SERM.USERLOC_ID=? AND SSM.MODULE_GBL=? AND ROLE_ID_GBL!=? " +
            " MINUS " +
            " SELECT SCREEN_SDESC FROM SYSADMIN_EMP_ROLE_MST WHERE USERLOC_ID=? AND ROLE_ID_GBL=? " +
            " ))AND SSM.MODULE_GBL=?";      
}

